import { describe, it, expect, beforeAll } from 'vitest';
import { createHash } from 'crypto';
import { sha256, hashEvidence, hashRecord, canonicalSerialize, verifyProvenanceChain } from '../server/services/integrity.js';
import { registerEvidence, getEvidence, verifyEvidence, simulateTamper } from '../server/services/evidence.js';
import { createCase, getCase } from '../server/services/case.js';
import { createProvenanceEvent, getEventsForCase, verifyChain } from '../server/services/provenance.js';
import { getDb } from '../server/db.js';

describe('CRYPTOGRAPHIC HASH VALIDATION AUDIT', () => {
  beforeAll(() => {
    getDb();
  });

  // ═══════════════════════════════════════════════════════
  // 1. EVIDENCE HASH — SOURCE CODE VERIFICATION
  // ═══════════════════════════════════════════════════════
  describe('1. Evidence Hash — Implementation Path Verification', () => {
    it('Hash uses Node.js crypto.createHash (trusted library)', () => {
      // integrity.js imports: import { createHash } from 'crypto';
      // sha256() calls: createHash('sha256').update(content).digest('hex')
      // This is the standard Node.js crypto module, not a custom implementation.
      const testContent = 'audit test content';
      const nodeHash = createHash('sha256').update(Buffer.from(testContent, 'utf-8')).digest('hex');
      const ourHash = sha256(testContent);
      expect(ourHash).toBe(nodeHash);
      expect(ourHash).toHaveLength(64);
    });

    it('Text evidence hashes actual UTF-8 content', () => {
      // sha256(string) → Buffer.from(string, 'utf-8') → createHash('sha256').update(buffer)
      const content = 'FPC-SORVAX AUDIT TEXT';
      const expectedHash = createHash('sha256').update(Buffer.from(content, 'utf-8')).digest('hex');
      const actualHash = hashEvidence(content);
      expect(actualHash).toBe(expectedHash);
    });

    it('Frontend cannot supply or override evidence hash', () => {
      // Register evidence through the service function directly
      // The registerEvidence function computes the hash internally:
      //   evidenceHash = hashEvidence(contentStr)
      // There is NO parameter for 'evidenceHash' in registerEvidence
      // The route handler also does NOT pass any hash from req.body
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Frontend Trust Audit',
        type: 'audit',
        content: 'This content should be hashed by backend',
      });

      // The hash was generated by backend, not supplied by caller
      expect(result.evidence_hash).toMatch(/^[a-f0-9]{64}$/);

      // Verify it matches what we'd calculate independently
      const expectedHash = hashEvidence('This content should be hashed by backend');
      expect(result.evidence_hash).toBe(expectedHash);
    });

    it('Hash is generated during registration, not pre-generated', () => {
      // The registerEvidence function computes hash AFTER receiving content:
      //   const contentStr = content || ...;
      //   const evidenceHash = hashEvidence(contentStr);
      // Then stores it in DB. The hash is not a parameter.
      // This is verified by the function signature not accepting a hash parameter.
      const content = 'Generated during registration test';
      const hash = hashEvidence(content);
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Registration Timing Audit',
        type: 'audit',
        content,
      });
      expect(result.evidence_hash).toBe(hash);
    });

    it('Filename is NOT used as evidence hash', () => {
      // The evidence hash is computed from content, not filename:
      //   evidenceHash = hashEvidence(contentStr)
      //   NOT: hashEvidence(fileName)
      const content = 'Actual evidence content';
      const fileName = 'different-filename.txt';
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Filename Audit',
        type: 'audit',
        content,
        fileName,
      });

      const hashOfContent = hashEvidence(content);
      const hashOfFilename = hashEvidence(fileName);
      expect(result.evidence_hash).toBe(hashOfContent);
      expect(result.evidence_hash).not.toBe(hashOfFilename);
    });

    it('Metadata alone is NOT used as evidence hash', () => {
      const content = 'Actual evidence content for metadata audit';
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Metadata Audit',
        type: 'audit',
        source: '/some/source',
        description: 'Some description',
        content,
      });

      const hashOfContent = hashEvidence(content);
      const hashOfMetadata = hashEvidence('Metadata Audit|Some description|/some/source');
      expect(result.evidence_hash).toBe(hashOfContent);
      expect(result.evidence_hash).not.toBe(hashOfMetadata);
    });
  });

  // ═══════════════════════════════════════════════════════
  // 2. REAL-TIME HASH TEST
  // ═══════════════════════════════════════════════════════
  describe('2. Real-Time Hash Test', () => {
    it('Known content produces expected SHA-256', () => {
      const content = 'FPC-SORVAX HASH TEST A';
      const expectedHash = createHash('sha256').update(Buffer.from(content, 'utf-8')).digest('hex');

      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Real-Time Hash Test A',
        type: 'audit',
        content,
      });

      expect(result.evidence_hash).toBe(expectedHash);
    });

    it('Same content → same SHA-256 (deterministic)', () => {
      const content = 'FPC-SORVAX HASH TEST A';

      const result1 = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Deterministic Test 1',
        type: 'audit',
        content,
      });

      const result2 = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Deterministic Test 2',
        type: 'audit',
        content,
      });

      expect(result1.evidence_hash).toBe(result2.evidence_hash);
    });

    it('DB-stored hash matches independently calculated hash', () => {
      const content = 'FPC-SORVAX HASH TEST A';
      const expectedHash = createHash('sha256').update(Buffer.from(content, 'utf-8')).digest('hex');

      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'DB Storage Verification',
        type: 'audit',
        content,
      });

      // Retrieve from DB
      const dbEvidence = getEvidence(result.evidence_id);
      expect(dbEvidence.evidence_hash).toBe(expectedHash);
    });
  });

  // ═══════════════════════════════════════════════════════
  // 3. ONE-BYTE CHANGE TEST
  // ═══════════════════════════════════════════════════════
  describe('3. One-Byte Change Test', () => {
    it('Content A ≠ Content B → Hash A ≠ Hash B', () => {
      const contentA = 'FPC-SORVAX HASH TEST A';
      const contentB = 'FPC-SORVAX HASH TEST B';

      const hashA = hashEvidence(contentA);
      const hashB = hashEvidence(contentB);

      expect(hashA).not.toBe(hashB);

      // Verify both are correct independently
      const expectedA = createHash('sha256').update(Buffer.from(contentA, 'utf-8')).digest('hex');
      const expectedB = createHash('sha256').update(Buffer.from(contentB, 'utf-8')).digest('hex');

      expect(hashA).toBe(expectedA);
      expect(hashB).toBe(expectedB);
    });

    it('Single character change produces different hash', () => {
      const original = 'Evidence content for change test';
      const modified = 'Evidence content for change TesX'; // last char changed

      const hashOriginal = hashEvidence(original);
      const hashModified = hashEvidence(modified);

      expect(hashOriginal).not.toBe(hashModified);

      // Both independently verified
      expect(hashOriginal).toBe(createHash('sha256').update(Buffer.from(original, 'utf-8')).digest('hex'));
      expect(hashModified).toBe(createHash('sha256').update(Buffer.from(modified, 'utf-8')).digest('hex'));
    });
  });

  // ═══════════════════════════════════════════════════════
  // 4. BINARY FILE TEST
  // ═══════════════════════════════════════════════════════
  describe('4. Binary File Test', () => {
    it('Base64 decoded to original bytes before hashing (NOT base64 string)', () => {
      // Create a known binary payload
      const originalBytes = Buffer.from([0x00, 0x01, 0x02, 0xFF, 0xFE, 0xFD, 0x80, 0x7F]);
      const base64String = originalBytes.toString('base64');

      // Expected: SHA-256 of the original bytes, NOT the base64 string
      const expectedHashFromBytes = createHash('sha256').update(originalBytes).digest('hex');
      const wrongHashFromBase64String = createHash('sha256').update(Buffer.from(base64String, 'utf-8')).digest('hex');

      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Binary Audit Test',
        type: 'binary',
        content: base64String,
        contentEncoding: 'base64',
        fileName: 'test-binary.bin',
        mimeType: 'application/octet-stream',
      });

      // MUST match hash of original bytes
      expect(result.evidence_hash).toBe(expectedHashFromBytes);
      // MUST NOT match hash of base64 string
      expect(result.evidence_hash).not.toBe(wrongHashFromBase64String);
    });

    it('Binary verification decodes base64 before re-hashing', () => {
      const originalBytes = Buffer.from([0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE]);
      const base64String = originalBytes.toString('base64');

      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Binary Verification Audit',
        type: 'binary',
        content: base64String,
        contentEncoding: 'base64',
        fileName: 'deadbeef.bin',
      });

      // Verify through the verification function
      const verification = verifyEvidence(result.evidence_id);
      expect(verification.verified).toBe(true);
      expect(verification.calculated_hash).toBe(verification.expected_hash);

      // And the expected hash should be SHA-256 of the original bytes
      const expectedFromBytes = createHash('sha256').update(originalBytes).digest('hex');
      expect(verification.expected_hash).toBe(expectedFromBytes);
    });

    it('UTF-8 text content hashed correctly through base64 path', () => {
      const textContent = 'Binary file test with UTF-8: café résumé naïve';
      const originalBytes = Buffer.from(textContent, 'utf-8');
      const base64String = originalBytes.toString('base64');

      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'UTF-8 Binary Audit',
        type: 'text',
        content: base64String,
        contentEncoding: 'base64',
        fileName: 'utf8-test.txt',
      });

      const expectedHash = createHash('sha256').update(originalBytes).digest('hex');
      expect(result.evidence_hash).toBe(expectedHash);
    });
  });

  // ═══════════════════════════════════════════════════════
  // 5. FRONTEND TRUST TEST
  // ═══════════════════════════════════════════════════════
  describe('5. Frontend Trust Test', () => {
    it('Backend ignores supplied hash — calculates its own', () => {
      const content = 'Frontend trust test content';
      const fakeHash = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';

      // Try to supply a fake hash through the service function
      // registerEvidence does NOT accept an 'evidenceHash' parameter
      // The hash is always computed from content
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Frontend Trust Test',
        type: 'audit',
        content,
        evidenceHash: fakeHash, // This parameter does NOT exist in the function
      });

      // The stored hash should be the REAL hash, not the fake one
      const realHash = hashEvidence(content);
      expect(result.evidence_hash).toBe(realHash);
      expect(result.evidence_hash).not.toBe(fakeHash);
    });

    it('Route handler does not forward any hash from request body', () => {
      // The route handler extracts specific fields from req.body:
      //   const { name, type, source, collectedBy, content, description, contentEncoding, fileName, fileSize, mimeType } = req.body;
      // It does NOT extract 'evidenceHash' or 'hash'
      // Then calls registerEvidence without any hash parameter
      // This is verified by the fact that registerEvidence computes hash internally
      const content = 'Route trust test content';
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Route Trust Test',
        type: 'audit',
        content,
      });

      expect(result.evidence_hash).toBe(hashEvidence(content));
    });

    it('Attacker cannot override hash by sending evidenceHash in JSON body', () => {
      // Even if the frontend sends { evidenceHash: "FAKE" }, the route handler
      // does not destructure 'evidenceHash' from req.body, so it's ignored.
      // registerEvidence() computes hash internally from content.
      const content = 'Attack vector test';
      const maliciousHash = '0000000000000000000000000000000000000000000000000000000000000000';

      // Even if we tried to pass it (which the function ignores)
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Attack Vector Test',
        type: 'audit',
        content,
        evidenceHash: maliciousHash, // Ignored by function
      });

      expect(result.evidence_hash).not.toBe(maliciousHash);
      expect(result.evidence_hash).toBe(hashEvidence(content));
    });
  });

  // ═══════════════════════════════════════════════════════
  // 6. RECORD HASH TEST
  // ═══════════════════════════════════════════════════════
  describe('6. Record Hash Test', () => {
    it('Record hash uses deterministic canonical serialization', () => {
      const record = {
        event_id: 'PE-TEST-001',
        case_id: 'CASE-0241',
        evidence_id: 'E-001',
        event_type: 'EVIDENCE_REGISTERED',
        actor_type: 'officer',
        actor_id: 'Officer Martinez',
        timestamp: '2026-08-30T10:44:00.000Z',
        description: 'Evidence registered',
        previous_record_hash: 'GENESIS',
      };

      const hash1 = hashRecord(record);
      const hash2 = hashRecord(record);
      expect(hash1).toBe(hash2);
    });

    it('Serialization order is fixed and documented', () => {
      // Fields are serialized in this exact order:
      // event_id | case_id | evidence_id | event_type | actor_type | actor_id | timestamp | description | previous_record_hash
      const record = {
        event_id: 'PE-TEST-002',
        case_id: 'CASE-0241',
        evidence_id: 'E-002',
        event_type: 'EVIDENCE_REGISTERED',
        actor_type: 'system',
        actor_id: 'system',
        timestamp: '2026-08-30T10:45:00.000Z',
        description: 'Test event',
        previous_record_hash: 'GENESIS',
      };

      const serialized = canonicalSerialize(record);
      const expected = 'PE-TEST-002|CASE-0241|E-002|EVIDENCE_REGISTERED|system|system|2026-08-30T10:45:00.000Z|Test event|GENESIS';
      expect(serialized).toBe(expected);
    });

    it('Null values become empty strings', () => {
      const record = {
        event_id: 'PE-TEST-003',
        case_id: 'CASE-0241',
        evidence_id: null,
        event_type: 'CASE_CREATED',
        actor_type: 'system',
        actor_id: 'system',
        timestamp: '2026-08-30T10:46:00.000Z',
        description: null,
        previous_record_hash: 'GENESIS',
      };

      const serialized = canonicalSerialize(record);
      const parts = serialized.split('|');
      expect(parts[2]).toBe(''); // evidence_id null → ''
      expect(parts[7]).toBe(''); // description null → ''
    });

    it('Record hash is generated by backend, not frontend', () => {
      // createProvenanceEvent() computes record hash internally:
      //   const recordHash = hashRecord(record);
      // The record is constructed from service-level data, not from request body
      const newCase = createCase({
        title: 'Record Hash Audit Case',
        severity: 'low',
      });

      const events = getEventsForCase(newCase.id);
      expect(events.length).toBeGreaterThanOrEqual(1);

      // Verify the record hash matches independent calculation
      const event = events[0];
      const record = {
        event_id: event.event_id,
        case_id: event.case_id,
        evidence_id: event.evidence_id || '',
        event_type: event.event_type,
        actor_type: event.actor_type,
        actor_id: event.actor_id,
        timestamp: event.timestamp,
        description: event.description || '',
        previous_record_hash: event.previous_record_hash,
      };

      const expectedHash = hashRecord(record);
      expect(event.record_hash).toBe(expectedHash);
    });

    it('Record hash is NOT supplied by frontend', () => {
      // The route handler for evidence registration:
      //   const { name, type, source, collectedBy, content, description, ... } = req.body;
      // It does NOT extract 'recordHash' from req.body
      // registerEvidence() calls createProvenanceEvent() which computes hash internally
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Record Hash Trust Test',
        type: 'audit',
        content: 'Record hash trust test',
      });

      // The record hash was generated by the backend
      expect(result.record_hash).toMatch(/^[a-f0-9]{64}$/);
    });
  });

  // ═══════════════════════════════════════════════════════
  // 7. PROVENANCE CHAIN TEST
  // ═══════════════════════════════════════════════════════
  describe('7. Provenance Chain Test', () => {
    it('Chain: GENESIS → CASE_CREATED → EVIDENCE_REGISTERED', () => {
      const newCase = createCase({
        title: 'Chain Audit Case',
        severity: 'medium',
        assignedTo: 'Auditor',
      });

      registerEvidence({
        caseId: newCase.id,
        name: 'Chain Audit Evidence',
        type: 'audit',
        content: 'Chain audit evidence content',
      });

      const events = getEventsForCase(newCase.id);
      expect(events.length).toBe(2);

      // Event 1: CASE_CREATED
      expect(events[0].event_type).toBe('CASE_CREATED');
      expect(events[0].previous_record_hash).toBe('GENESIS');

      // Event 2: EVIDENCE_REGISTERED
      expect(events[1].event_type).toBe('EVIDENCE_REGISTERED');
      expect(events[1].previous_record_hash).toBe(events[0].record_hash);

      // Chain verification should pass
      const chainResult = verifyChain(newCase.id);
      expect(chainResult.chain_valid).toBe(true);
    });

    it('Chain with multiple evidence: GENESIS → CASE_CREATED → EVIDENCE_REGISTERED × 2', () => {
      const newCase = createCase({
        title: 'Multi Evidence Chain Audit',
        severity: 'low',
      });

      registerEvidence({
        caseId: newCase.id,
        name: 'Evidence 1',
        type: 'file',
        content: 'First evidence content',
      });

      registerEvidence({
        caseId: newCase.id,
        name: 'Evidence 2',
        type: 'file',
        content: 'Second evidence content',
      });

      const events = getEventsForCase(newCase.id);
      expect(events.length).toBe(3);
      expect(events[0].event_type).toBe('CASE_CREATED');
      expect(events[1].event_type).toBe('EVIDENCE_REGISTERED');
      expect(events[2].event_type).toBe('EVIDENCE_REGISTERED');

      // Each event's previous_record_hash points to the previous event's record_hash
      expect(events[1].previous_record_hash).toBe(events[0].record_hash);
      expect(events[2].previous_record_hash).toBe(events[1].record_hash);

      const chainResult = verifyChain(newCase.id);
      expect(chainResult.chain_valid).toBe(true);
    });

    it('Modified provenance field → CHAIN VALIDATION FAILED', () => {
      const newCase = createCase({
        title: 'Chain Tamper Audit',
        severity: 'low',
      });

      registerEvidence({
        caseId: newCase.id,
        name: 'Tamper Audit Evidence',
        type: 'audit',
        content: 'Tamper audit content',
      });

      // First verify chain is valid
      let chainResult = verifyChain(newCase.id);
      expect(chainResult.chain_valid).toBe(true);

      // Tamper with a provenance event description in the database
      const db = getDb();
      const events = getEventsForCase(newCase.id);
      const eventIdToTamper = events[1].event_id; // Tamper with the evidence event

      db.prepare('UPDATE provenance_events SET description = ? WHERE event_id = ?')
        .run('TAMPERED DESCRIPTION', eventIdToTamper);

      // Verify chain is now invalid
      chainResult = verifyChain(newCase.id);
      expect(chainResult.chain_valid).toBe(false);

      // The tampered event should fail hash validation
      const tamperedEventResult = chainResult.events.find(e => e.event_id === eventIdToTamper);
      expect(tamperedEventResult.hash_valid).toBe(false);

      // Restore original
      db.prepare('UPDATE provenance_events SET description = ? WHERE event_id = ?')
        .run(events[1].description, eventIdToTamper);

      // Verify chain is valid again
      chainResult = verifyChain(newCase.id);
      expect(chainResult.chain_valid).toBe(true);
    });
  });

  // ═══════════════════════════════════════════════════════
  // 8. EVIDENCE TAMPER TEST
  // ═══════════════════════════════════════════════════════
  describe('8. Evidence Tamper Test', () => {
    it('Tampered evidence → verification returns COMPROMISED', () => {
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Tamper Audit Evidence',
        type: 'audit',
        content: 'Original content for tamper audit',
      });

      const originalHash = result.evidence_hash;

      // Tamper with the evidence
      const tamperResult = simulateTamper(result.evidence_id);
      expect(tamperResult.status).toBe('tampered');
      expect(tamperResult.original_hash).toBe(originalHash);

      // Verify should detect the tamper
      const verification = verifyEvidence(result.evidence_id);
      expect(verification.verified).toBe(false);
      expect(verification.status).toBe('COMPROMISED');

      // The calculated hash (of tampered content) should differ from stored hash
      expect(verification.calculated_hash).not.toBe(verification.expected_hash);
      expect(verification.expected_hash).toBe(originalHash);
    });

    it('Tamper detection is based on actual content comparison', () => {
      const originalContent = 'Integrity test content for tamper verification';
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Content Comparison Audit',
        type: 'audit',
        content: originalContent,
      });

      // The stored hash should be SHA-256 of the original content
      expect(result.evidence_hash).toBe(hashEvidence(originalContent));

      // After tamper, the content changes
      const tamperResult = simulateTamper(result.evidence_id);
      const dbEvidence = getEvidence(result.evidence_id);

      // The content in DB should now be different
      expect(dbEvidence.content).not.toBe(originalContent);

      // The stored hash is still the original hash
      expect(dbEvidence.evidence_hash).toBe(hashEvidence(originalContent));

      // But the current content produces a different hash
      expect(hashEvidence(dbEvidence.content)).not.toBe(dbEvidence.evidence_hash);
    });

    it('Verification re-hashes actual stored content and compares', () => {
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Re-hash Audit',
        type: 'audit',
        content: 'Content for re-hash audit',
      });

      // verifyEvidence() reads content from DB and re-hashes it
      // Then compares with stored evidence_hash
      const verification = verifyEvidence(result.evidence_id);
      expect(verification.verified).toBe(true);
      expect(verification.calculated_hash).toBe(verification.expected_hash);

      // Tamper and verify again
      simulateTamper(result.evidence_id);
      const verification2 = verifyEvidence(result.evidence_id);
      expect(verification2.verified).toBe(false);
    });
  });

  // ═══════════════════════════════════════════════════════
  // 9. CRITICAL SECURITY ANALYSIS
  // ═══════════════════════════════════════════════════════
  describe('9. Critical Security Analysis', () => {
    it('A. Protects against accidental evidence modification', () => {
      // Evidence hash is computed from content at registration time
      // Any modification to content will produce a different hash
      // Verification detects this via hash comparison
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Accidental Modification Audit',
        type: 'audit',
        content: 'Original accidental modification test',
      });

      // Before tamper: verified
      let verification = verifyEvidence(result.evidence_id);
      expect(verification.verified).toBe(true);

      // After tamper: compromised
      simulateTamper(result.evidence_id);
      verification = verifyEvidence(result.evidence_id);
      expect(verification.verified).toBe(false);
      // VERDICT: PROTECTED
    });

    it('B. Protects against evidence corruption', () => {
      // Same mechanism as accidental modification
      // Hash comparison detects any content change
      // VERDICT: PROTECTED (same as A)
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Corruption Audit',
        type: 'audit',
        content: 'Corruption test content',
      });

      const originalHash = result.evidence_hash;
      simulateTamper(result.evidence_id);

      const dbEvidence = getEvidence(result.evidence_id);
      expect(dbEvidence.evidence_hash).toBe(originalHash);
      expect(hashEvidence(dbEvidence.content)).not.toBe(originalHash);
    });

    it('C. Protects against evidence replacement', () => {
      // If someone replaces evidence content entirely
      // The hash won't match the new content
      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Replacement Audit',
        type: 'audit',
        content: 'Original evidence for replacement test',
      });

      const originalHash = result.evidence_hash;

      // Simulate replacement by changing content entirely
      const db = getDb();
      db.prepare('UPDATE evidence SET content = ? WHERE evidence_id = ?')
        .run('Completely different evidence content', result.evidence_id);

      const verification = verifyEvidence(result.evidence_id);
      expect(verification.verified).toBe(false);
      expect(verification.expected_hash).toBe(originalHash);
      // VERDICT: PROTECTED
    });

    it('D. Protects against modification of provenance records', () => {
      const newCase = createCase({
        title: 'Provenance Protection Audit',
        severity: 'low',
      });

      const events = getEventsForCase(newCase.id);
      const eventId = events[0].event_id;

      // Original chain is valid
      let chainResult = verifyChain(newCase.id);
      expect(chainResult.chain_valid).toBe(true);

      // Modify a provenance field
      const db = getDb();
      db.prepare('UPDATE provenance_events SET actor_id = ? WHERE event_id = ?')
        .run('TAMPERED_ACTOR', eventId);

      // Chain should be invalid
      chainResult = verifyChain(newCase.id);
      expect(chainResult.chain_valid).toBe(false);

      // Restore
      db.prepare('UPDATE provenance_events SET actor_id = ? WHERE event_id = ?')
        .run(events[0].actor_id, eventId);

      chainResult = verifyChain(newCase.id);
      expect(chainResult.chain_valid).toBe(true);
      // VERDICT: PROTECTED
    });

    it('E. CRITICAL: Database-level attacker can modify both evidence AND hash', () => {
      // This test demonstrates the fundamental limitation:
      // If an attacker has direct database access, they can modify:
      //   1. evidence.content (the evidence itself)
      //   2. evidence.evidence_hash (the stored hash)
      // Both can be changed simultaneously, making verification pass
      // even though the evidence was altered.
      //
      // This is NOT a bug — it is a fundamental property of hash-based integrity.
      // Hash verification alone cannot protect against an attacker who controls
      // the database.
      //
      // To protect against this, you would need:
      //   - External/immutable audit log
      //   - Hardware security module (HSM)
      //   - Blockchain/distributed ledger
      //   - Digital signatures with external key
      //
      // Current architecture: GENESIS → CASE_CREATED → EVIDENCE_REGISTERED
      // The hash is stored in the SAME database as the evidence.
      // A database-level attacker can modify both.

      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Database Attacker Audit',
        type: 'audit',
        content: 'Original content for database attacker test',
      });

      const originalHash = result.evidence_hash;

      // Attacker modifies BOTH content and hash
      const db = getDb();
      const newContent = 'ATTACKER REPLACED THIS EVIDENCE';
      const newHash = hashEvidence(newContent);

      db.prepare('UPDATE evidence SET content = ?, evidence_hash = ? WHERE evidence_id = ?')
        .run(newContent, newHash, result.evidence_id);

      // Verification PASSES even though evidence was replaced
      const verification = verifyEvidence(result.evidence_id);
      expect(verification.verified).toBe(true); // This is the expected (concerning) result

      // VERDICT: NOT PROTECTED against database-level attacker
      // Hash verification alone cannot provide protection if an attacker
      // can modify both the evidence and its trusted hash.
    });
  });

  // ═══════════════════════════════════════════════════════
  // 10. TWO-HASH MODEL VALIDATION
  // ═══════════════════════════════════════════════════════
  describe('10. Two-Hash Model Validation', () => {
    it('Hash #1: Evidence Hash = SHA-256(actual evidence bytes)', () => {
      const content = 'Two hash model test content';
      const expectedHash = createHash('sha256').update(Buffer.from(content, 'utf-8')).digest('hex');

      const result = registerEvidence({
        caseId: 'CASE-0241',
        name: 'Two Hash Model Test',
        type: 'audit',
        content,
      });

      expect(result.evidence_hash).toBe(expectedHash);
      // Evidence Hash proves: evidence integrity
    });

    it('Hash #2: Record Hash = SHA-256(canonical provenance record)', () => {
      const newCase = createCase({
        title: 'Record Hash Model Audit',
        severity: 'low',
      });

      registerEvidence({
        caseId: newCase.id,
        name: 'Record Hash Model Evidence',
        type: 'audit',
        content: 'Record hash model test',
      });

      const events = getEventsForCase(newCase.id);
      const event = events[0];

      // Reconstruct the record and compute hash independently
      const record = {
        event_id: event.event_id,
        case_id: event.case_id,
        evidence_id: event.evidence_id || '',
        event_type: event.event_type,
        actor_type: event.actor_type,
        actor_id: event.actor_id,
        timestamp: event.timestamp,
        description: event.description || '',
        previous_record_hash: event.previous_record_hash,
      };

      const serialized = canonicalSerialize(record);
      const expectedRecordHash = createHash('sha256').update(Buffer.from(serialized, 'utf-8')).digest('hex');

      expect(event.record_hash).toBe(expectedRecordHash);
    });

    it('Previous Record Hash links events in chain', () => {
      const newCase = createCase({
        title: 'Chain Link Model Audit',
        severity: 'low',
      });

      registerEvidence({
        caseId: newCase.id,
        name: 'Chain Link Evidence 1',
        type: 'audit',
        content: 'Chain link 1',
      });

      registerEvidence({
        caseId: newCase.id,
        name: 'Chain Link Evidence 2',
        type: 'audit',
        content: 'Chain link 2',
      });

      const events = getEventsForCase(newCase.id);

      // Each event's previous_record_hash must equal the prior event's record_hash
      expect(events[0].previous_record_hash).toBe('GENESIS');
      expect(events[1].previous_record_hash).toBe(events[0].record_hash);
      expect(events[2].previous_record_hash).toBe(events[1].record_hash);

      // Three distinct proofs:
      // 1. Evidence Hash → evidence integrity (each evidence item)
      // 2. Record Hash → record integrity (each provenance event)
      // 3. Previous Record Hash → chain integrity (event linking)
    });
  });
});
